language: node_js
node_js:
    - "4.0.0"
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install -g bower grunt-cli codacy-coverage coveralls
    - bower install --force-latest
after_script:
    - cat coverage/**/lcov.info | codacy-coverage
    - cat coverage/**/lcov.info | coveralls
before_deploy:
    - grunt build:package
deploy:
  provider: bintray
  file: "bintray.json"
  user: "psbrandt"
  key: $BINTRAY_API_KEY
  dry-run: false
